# Generated by Django 5.2.5 on 2025-08-21 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_realestate_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='likes',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
