# Generated by Django 5.2.5 on 2025-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_realestaterating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
