# Generated by Django 5.2.5 on 2025-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_realestatecomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram'),
        ),
    ]
