# Generated by Django 5.2.5 on 2025-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_realestate_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
