# Generated by Django 5.2.5 on 2025-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_realestate_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
