# Generated by Django 5.2.5 on 2025-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_districtmultiplier_pricingconfig_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('uchastok', 'Участок'), ('novostroyka', 'Новостройка'), ('vtorichka', 'Вторичка'), ('kommersiya', 'Коммерция'), ('dom', 'Дом')], max_length=50)),
                ('median_price_m2', models.FloatField()),
                ('sample_size', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
