# Generated by Django 5.2.5 on 2025-09-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_marketstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('uchastok', 'Участок'), ('novostroyka', 'Новостройка'), ('vtorichka', 'Вторичка'), ('kommersiya', 'Коммерческое помещение'), ('arenda', 'Аренда')], max_length=50, verbose_name='Тип недвижимости')),
                ('district', models.CharField(choices=[('bekt', 'Бектемирский район'), ('chil', 'Чиланзарский район'), ('yash', 'Яшнободский район'), ('mirab', 'Мирабадский район'), ('mu', 'Мирзо-Улугбекский район'), ('serg', 'Сергелийский район'), ('shayx', 'Шайхантахурский район'), ('almaz', 'Алмазарский район'), ('uch', 'Учтепинский район'), ('yakka', 'Яккасарайский район'), ('yunus', 'Юнусабадский район')], max_length=50, verbose_name='Район')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Площадь (м²)')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Площадь участка (сотки)')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('condition', models.CharField(blank=True, choices=[('evroremont', 'Евроремонт'), ('chistyy', 'Чистый ремонт'), ('bez_remonta', 'Без ремонта'), ('trebuet', 'Требует ремонт')], max_length=50, null=True, verbose_name='Состояние')),
                ('has_furniture', models.BooleanField(default=False, verbose_name='С мебелью')),
                ('has_appliances', models.BooleanField(default=False, verbose_name='С техникой')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Есть парковка')),
                ('has_renters', models.BooleanField(default=False, verbose_name='Есть арендаторы')),
                ('facade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фасад')),
                ('building_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название новостройки')),
                ('line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Линия')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Арендная плата (USD)')),
                ('base_price_m2', models.DecimalField(decimal_places=2, default=800, max_digits=12, verbose_name='Цена за 1 м² (USD)')),
                ('base_price_sotix', models.DecimalField(decimal_places=2, default=1000, max_digits=12, verbose_name='Цена за 1 сотку (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
        ),
        migrations.DeleteModel(
            name='DistrictMultiplier',
        ),
        migrations.DeleteModel(
            name='MarketStat',
        ),
        migrations.DeleteModel(
            name='PricingConfig',
        ),
    ]
